import os


class ConfiguracaoNotificacoes:
    ATIVO = os.getenv('NOTIFICACOES_ATIVO', '0').strip().lower() in ('1', 'true', 'yes', 'on')
    WHATSAPP_ATIVO = os.getenv('WHATSAPP_ATIVO', '0').strip().lower() in ('1', 'true', 'yes', 'on')
    WHATSAPP_EVOLUTION_URL = os.getenv('WHATSAPP_EVOLUTION_URL', '').rstrip('/')
    WHATSAPP_EVOLUTION_APIKEY = os.getenv('WHATSAPP_EVOLUTION_APIKEY', '')
    WHATSAPP_EVOLUTION_INSTANCE = os.getenv('WHATSAPP_EVOLUTION_INSTANCE', '')
    WHATSAPP_GRUPO_PRODUCAO = os.getenv('WHATSAPP_GRUPO_PRODUCAO', '')
    WHATSAPP_TIMEOUT = int(os.getenv('WHATSAPP_TIMEOUT', '10'))
    WHATSAPP_RETRIES = int(os.getenv('WHATSAPP_RETRIES', '2'))
    FILA_ATIVA = os.getenv('NOTIFICACOES_FILA_ATIVA', '1').strip().lower() in ('1', 'true', 'yes', 'on')
    SCHEDULER_ATIVO = os.getenv('NOTIFICACOES_SCHEDULER_ATIVO', '0').strip().lower() in ('1', 'true', 'yes', 'on')
    MONITORAMENTO_INTERVALO_SEGUNDOS = int(os.getenv('MONITORAMENTO_INTERVALO_SEGUNDOS', '60'))
    ALERTA_SERVICO_PARADO_MINUTOS = int(os.getenv('ALERTA_SERVICO_PARADO_MINUTOS', '25'))
    ALERTA_SETUP_LONGO_MINUTOS = int(os.getenv('ALERTA_SETUP_LONGO_MINUTOS', '60'))
    ALERTA_PAUSA_EXCESSIVA_MINUTOS = int(os.getenv('ALERTA_PAUSA_EXCESSIVA_MINUTOS', '30'))


EXEMPLO_ENV = '''
# Notificacoes industriais
NOTIFICACOES_ATIVO=1
NOTIFICACOES_FILA_ATIVA=1
NOTIFICACOES_SCHEDULER_ATIVO=1
MONITORAMENTO_INTERVALO_SEGUNDOS=60
ALERTA_SERVICO_PARADO_MINUTOS=25
ALERTA_SETUP_LONGO_MINUTOS=60
ALERTA_PAUSA_EXCESSIVA_MINUTOS=30

# WhatsApp Evolution API
WHATSAPP_ATIVO=1
WHATSAPP_EVOLUTION_URL=https://sua-evolution-api.com
WHATSAPP_EVOLUTION_APIKEY=sua_api_key
WHATSAPP_EVOLUTION_INSTANCE=sua_instancia
WHATSAPP_GRUPO_PRODUCAO=120363000000000000@g.us
WHATSAPP_TIMEOUT=10
WHATSAPP_RETRIES=2
'''
